var num = 1;
var str = "一个人的自身越是丰富，就越难以忍受世俗常规的安排";
var bool = true;
var obj = {};
var n = null;
var u = undefined;
console.log(typeof num); // number
console.log(typeof str); // string
console.log(typeof bool); // boolean
console.log(typeof obj); // object
console.log(typeof n); // object
console.log(typeof u); // undefined
