name: syncToGitee
on:
  push:
    branches:
      - gh-pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: okou19900722/gitee-pages@v1
        with:
          username: "cdy1998cdy@163.com"
          password: ${{ secrets.GITEE_PASSWORD }}
          repository: "knowledge-has-no-limit"
          branch: "gh-pages"
          directory: "./"
          #是否开启https
          https: true
